backend:
  name: git-gateway
  branch: main

local_backend: true
publish_mode: editorial_workflow

# Local netlifyCMS login with $ npx netlify-cms-proxy-server

media_folder: static/uploads
public_folder: /uploads

collections:
  - name: 'pages'
    label: 'Pages'
    media_folder: ''
    public_folder: ''
    files:
      - file: './src/pages/index.md'
        name: 'home'
        label: 'Homepage'
        editor:
          preview: false
        fields:
          - { label: 'TemplateKey', name: 'templateKey', widget: hidden }
          - { label: 'Title', name: 'title', widget: 'string', required: true }
          - { label: 'Image', name: 'image', widget: 'image', required: false }
          - {
              label: 'Description',
              name: 'description',
              widget: 'string',
              required: true,
            }
      - file: './src/pages/contact/index.md'
        name: 'contact'
        label: 'Contact'
        editor:
          preview: false
        fields:
          - { label: 'TemplateKey', name: 'templateKey', widget: hidden }
          - { label: 'Title', name: 'title', widget: 'string', required: true }
          - { label: 'Image', name: 'image', widget: 'image', required: false }
          - {
              label: 'Description',
              name: 'description',
              widget: 'string',
              required: true,
            }
